frontend:
  image: my-registry/frontend:latest
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
backend:
  image: my-registry/backend:latest
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1"
ingress:
  enabled: true
  host: my-app.example.com
  path: "/"
  pathType: Prefix
  serviceName: {{ .Release.Name }}-frontend
  servicePortName: http